services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth-service
    image: jhoncee2018/hrms-auth-api:latest
    container_name: hrms-auth-api
    restart: always
    ports:
      - "8083:8080" # Map to 8082 as requested
    networks:
      - tenantstorenet
    env_file:
      - .env

  tenant-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: tenant-service
    image: jhoncee2018/hrms-tenant-api:latest
    container_name: hrms-tenant-api
    restart: always
    ports:
      - "8084:8080"
    networks:
      - tenantstorenet
    env_file:
      - .env

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: notification-service
    image: jhoncee2018/hrms-notification:latest
    container_name: hrms-notification
    restart: always
    ports:
      - "8085:8080"
    networks:
      - tenantstorenet
    env_file:
      - .env

# --- Global Config ---
networks:
  tenantstorenet:
    driver: bridge
