services:
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - hrmsnet
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hrmsnet
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - hrmsnet
    depends_on:
      - redis
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth-service
    image: jhoncee2018/hrms-auth-api:latest
    container_name: hrms-auth-api
    restart: always
    ports:
      - "8083:8080" # Map to 8082 as requested
    networks:
      - hrmsnet
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  tenant-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: tenant-service
    image: jhoncee2018/hrms-tenant-api:latest
    container_name: hrms-tenant-api
    restart: always
    ports:
      - "8084:8080"
    networks:
      - hrmsnet
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: notification-service
    image: jhoncee2018/hrms-notification:latest
    container_name: hrms-notification
    restart: always
    ports:
      - "8085:8080"
    networks:
      - hrmsnet
    env_file:
      - .env

# --- Global Config ---
networks:
  hrmsnet:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
