services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    stop_grace_period: 2s
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - hrmsnet
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    stop_grace_period: 2s
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
      - HTTP_USER=${REDIS_COMMANDER_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
    ports:
      - "8088:8081"
    networks:
      - hrmsnet
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    stop_grace_period: 2s
    entrypoint: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_shovel rabbitmq_shovel_management && exec docker-entrypoint.sh rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hrmsnet
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: always
    stop_grace_period: 2s
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - hrmsnet
    volumes:
      - loki_data:/loki
    deploy:
      resources:
        limits:
          memory: 200M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "5342:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    networks:
      - hrmsnet
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      resources:
        limits:
          memory: 200M

networks:
  hrmsnet:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data:
  loki_data:
  grafana_data: