<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>OnePunch.Auth.Api</RootNamespace>
		<UserSecretsId>6ab3ffce-21b1-49ae-b1ea-b5cc937f2e9b</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mapster" />
		<PackageReference Include="Mapster.DependencyInjection" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.AspNetCore.HeaderPropagation" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
		<PackageReference Include="Serilog.Sinks.Loki" />
		<PackageReference Include="StackExchange.Redis" />
		<PackageReference Include="Grpc.Tools" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Hosting" /> 
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Exceptions" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Refit.HttpClientFactory" />
		<PackageReference Include="MessagePack.AspNetCoreMvcFormatter" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Onepunch.Auth.Core\Onepunch.Auth.Core.csproj" />
	  <ProjectReference Include="..\Onepunch.Auth.Domain\Onepunch.Auth.Domain.csproj" />
	</ItemGroup>


</Project>
