<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Onepunch.Common.Lib</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mapster" />
		<PackageReference Include="Mapster.DependencyInjection" />
		<PackageReference Include="Polly" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Refit.HttpClientFactory" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="Serilog.Sinks.Loki" />
		<PackageReference Include="StackExchange.Redis" />
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="Microsoft.Extensions.Hosting " />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
	</ItemGroup>


</Project>
