<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>TenantStoreApi.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Exceptions\**" />
		<Compile Remove="Messaging\Message Handlers\**" />
		<EmbeddedResource Remove="Exceptions\**" />
		<EmbeddedResource Remove="Messaging\Message Handlers\**" />
		<None Remove="Exceptions\**" />
		<None Remove="Messaging\Message Handlers\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Protos\tenant.proto" />
	</ItemGroup>
	<ItemGroup>
		<Protobuf Include="Protos\checkemail.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\tenant.proto" GrpcServices="Server" />
		<PackageReference Include="MassTransit.RabbitMQ" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="MessagePack.AspNetCoreMvcFormatter" />
		<PackageReference Include="MessagePackAnalyzer" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.AspNetCore" />
		<PackageReference Include="Grpc.Tools" />
		<PackageReference Include="MassTransit" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Polly" />
		<PackageReference Include="RabbitMQ.Client" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Exceptions" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />

	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Onepunch.Common.Lib\Onepunch.Common.Lib.csproj" />
		<ProjectReference Include="..\TenantStoreApi.Domain\TenantStoreApi.Domain.csproj" />
		<ProjectReference Include="..\TenantStoreApi.Infrastructure\TenantStoreApi.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Interfaces\" />
	</ItemGroup>

</Project>
