<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Messaging\Message Handlers\**" />
	  <EmbeddedResource Remove="Messaging\Message Handlers\**" />
	  <None Remove="Messaging\Message Handlers\**" />
	</ItemGroup>
	
	<ItemGroup>
		<Protobuf Include="Protos\tenant.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\checkemail.proto" GrpcServices="Server" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.AspNetCore" />
		<PackageReference Include="Grpc.Tools" />
		<PackageReference Include="Confluent.Kafka" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="AutoMapper" />

		<PackageReference Include="Microsoft.IdentityModel.Tokens" />

		<PackageReference Include="Polly" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />

		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Onepunch.Auth.Domain\Onepunch.Auth.Domain.csproj" />
		<ProjectReference Include="..\Onepunch.Auth.Infrastructure\Onepunch.Auth.Infrastructure.csproj" />
		<ProjectReference Include="..\Onepunch.Common.Lib\Onepunch.Common.Lib.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="Protos\checkemail.proto">
	    <GrpcServices>Client</GrpcServices>
	  </None>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Utilities\" />
	</ItemGroup>
</Project>
