<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>OnePunch.Auth.Api</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.AspNetCore.HeaderPropagation" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Grpc.Tools" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Hosting" /> 
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Onepunch.Auth.Core\Onepunch.Auth.Core.csproj" />
	  <ProjectReference Include="..\Onepunch.Auth.Domain\Onepunch.Auth.Domain.csproj" />
	</ItemGroup>


</Project>
